FROM node:22-bookworm

ARG USERNAME=vscode

# Instala pacotes e cria usuário com UID/GID 1000
RUN apt-get update && apt-get install -y --no-install-recommends nano \
      git curl sudo ca-certificates bash gnupg2 && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd $USERNAME && \
    useradd -m -g $USERNAME -s /bin/bash $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# Instalação de pacotes globais do npm
RUN npm install -g npm@11.4.0 \
  && npm install -g @angular/cli@19.2.13 \
  && npm cache clean --force

# Desativa telemetria do Angular CLI
ENV NG_CLI_ANALYTICS=false

# Copia script de inicialização e dá permissão
COPY .devcontainer/dev-start.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Define usuário padrão e diretório de trabalho
USER $USERNAME
WORKDIR /workspace

ENTRYPOINT ["/entrypoint.sh"]