FROM eclipse-temurin:21-jdk

WORKDIR /app

RUN apt-get update && apt-get install -y git maven nano \
  && rm -rf /var/lib/apt/lists/*

# Clone o projeto
RUN git clone https://github.com/chiarelli/estoqueProdutos.git

WORKDIR /app/estoqueProdutos

RUN mvn clean install -DskipTests

EXPOSE 8080
CMD ["mvn", "clean", "spring-boot:run", "-Dspring-boot.run.arguments=--server.address=0.0.0.0"]